@switch(Auth::user()->type)
  @case("admsuper")
      @include('users.adm')
      @break
  @case("adm")
      @include('users.adm')
      @break
  @case("driver")
      @include('users.driver')
      @break
  @default
      @include('error.index')
@endswitch
