@switch(Auth::user()->type)
    @case("inspector")
        @include('infringements.inspector')
        @break
    @case("judge")
        @include('infringements.judge')
        @break
    @case("driver")
        @include('infringements.driver')
        @break
    @default
        @include('error.index')
@endswitch
