@switch(Auth::user()->type)
    @case("driver")
        @include('credit.driver')
        @break
    @case("local")
        @include('credit.local')
        @break
    @default
        @include('error.index')
@endswitch
