@switch(Auth::user()->type)
    @case("admsuper")
        @include('spacereservations.admin')
        @break
    @case("adm")
        @include('spacereservations.admin')
        @break
    @case("inspector")
        @include('spacereservations.inspector')
        @break
    @default
        @include('error.index')
@endswitch
